name: 'Setup SSH and GPG Keys'
description: 'Configures SSH and GPG keys for Git operations'

inputs:
  ssh_private_key:
    description: 'The private SSH key'
    required: true
  gpg_private_key:
    description: 'The GPG private key'
    required: true
  gpg_passphrase:
    description: 'The passphrase for the GPG key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure Git User
      shell: bash
      run: |
        git config --global user.name "${{ env.USERNAME }}"
        git config --global user.email "${{ env.USER_EMAIL }}"

    - name: Import SSH Key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519
        echo "SSH key configured."

    - name: Import GPG Key
      shell: bash
      run: |
        echo "${{ inputs.gpg_private_key }}" | gpg --batch --import
        GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format=long | awk '/sec/{print $2}' | cut -d'/' -f2 | head -n1)
        git config --global user.signingkey "$GPG_KEY_ID"
        git config --global commit.gpgsign true
        echo "${{ inputs.gpg_passphrase }}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --sign --detach-sign
        echo "GPG key configured for signing."
